name: Deploy static content to Pages

on:
  # Uruchamia akcję po zmergowaniu/pushu do gałęzi main lub master
  push:
    branches: ["main", "master"]
  # Pozwala na ręczne uruchomienie akcji z zakładki Actions
  workflow_dispatch:

# Nadanie niezbędnych uprawnień dla GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Konfiguracja współbieżności - chroni przed jednoczesnym wdrażaniem wielu wersji
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Zadanie wdrożenia
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Ścieżka do katalogu, w którym znajdują się pliki do publikacji (w tym wypadku główny katalog z index.html)
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
